import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ banks, errorCode }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {banks.map((item) => (
            <li key={item.id}>{item.label}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context) {
  const requestOptions = {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.JWT_TOKEN}`,
    },
  };
  let banks, errorCode, sortedBank;
  try {
    const data = await fetch(
      `${process.env.API_URL}/Admin/GetBank`,
      requestOptions
    );

    banks = await data.json();
  } catch (err) {
    errorCode = 500;
  }

  if (!banks) {
    errorCode = 500;
  }

  return {
    props: {
      errorCode: errorCode ? errorCode : null,
      banks: banks?.result ? banks.result : null,
    },
  };
}
